* src/vm/resolve.c (resolve_class_from_name): Call exceptions_classnotfoundexception_to_noclassdeffounderror in exception case.
* src/vm/exceptions.c (vmcore/method.h): Added.
(exceptions_throw_utf_throwable): Added object-initialize code.
(exceptions_throw_utf_exception): Likewise.
(exceptions_throw_noclassdeffounderror_cause): New function.
(classnotfoundexception_to_noclassdeffounderror): Renamed to
exceptions_classnotfoundexception_to_noclassdeffounderror.
(exceptions_print_stacktrace): Don't use exceptionptr directly.

* src/vm/exceptions.h (exceptions_throw_noclassdeffounderror_cause):
Added.
(classnotfoundexception_to_noclassdeffounderror): Renamed to
exceptions_classnotfoundexception_to_noclassdeffounderror.

* src/vm/vm.c (opts): Added XX:.
(vm_create): Likewise.
(vm_run): Call exceptions_throw_noclassdeffounderror_cause when
main-class is not found.

* src/native/vm/java_lang_Class.c (forName): Don't convert exception.

* src/native/vm/gnu/java_lang_VMClassLoader.c (getPrimitiveClass): Use
primitive_class_get_by_char.
(loadClass): Don't convert exception.

* src/native/native.c (native_new_and_init_string): Use
class_findmethod instead of class_resolveclassmethod.
(native_new_and_init_throwable): Removed.
(native_new_and_init_exception): Likewise.

* src/native/native.h (native_new_and_init_throwable): Removed.
(native_new_and_init_exception): Likewise.

* src/vmcore/class.c (class_array_of): Smaller code changes.

* src/vmcore/loader.c (vmcore/primitive.h): Added.
(load_class_from_classloader): Don't convert exception.
(load_class_bootstrap): Throw ClassNotFoundException instead of
NoClassDefFoundError.
(load_newly_created_array): Likewise, check if primitive-array type is
valid.

* src/vmcore/utf8.c (utf_initCause): Added.
(utf_java_lang_Throwable__java_lang_Throwable): Likewise.
(utf8_init): Initialize new variables.

* src/vmcore/utf8.h (utf_initCause): Added.
(utf_java_lang_Throwable__java_lang_Throwable): Likewise.

* src/cacaoh/dummy.c (exceptions_throw_classnotfoundexception): New
function.
(classnotfoundexception_to_noclassdeffounderror): Removed.

* src/vmcore/options.c (options_xx): New function.
* src/vmcore/options.h (options_xx): Added.