* src/vm/string.c, src/vm/stringlocal.h (java_string_new_char): Renamed to `java_string_new_from_ascii` to make more clear what this function does. It is wrong to use this function to create a java.lang.String from a buffer of UTF-8 characters!
* src/vm/finalizer.c (finalizer_start_thread): Legitimate use.
* src/vm/jit/profile/profile.c (profile_start_thread): Likewise.

* src/vm/exceptions.c
(exceptions_new_linkageerror): Definitely INCORRECT use.
(exceptions_new_nosuchmethoderror): Likewise.
* src/native/vm/VMRuntime.c
(Java_java_lang_VMRuntime_mapLibraryName): Likewise.

* src/vm/exceptions.c (new_exception_message): Probably INCORRECT use.
* src/native/jni.c (DefineClass): Likewise.
(ThrowNew): Likewise.
* src/native/vm/VMClassLoader.c
(Java_java_lang_VMClassLoader_nativeGetResources): Likewise.

* src/vm/properties.c (properties_system_add): Needs review.
* src/cacao/cacao.c (getmainclassnamefromjar): Likewise.
* src/native/jvmti/cacaodbg.c (setup_jdwp_thread): Likewise.
* src/native/jvmti/jvmti.c (CreateRawMonitor, GetSystemProperty)
(SetSystemProperty): Likewise.