* src/vm/jit/methodheader.h (MethodPointer): Removed. (CodeinfoPointer): Added.
* src/vm/method.c (method_vftbl_lookup): Use CodeinfoPointer.

* src/vm/jit/powerpc/codegen.c (codegen): Use codeinfo instead of
methodinfo.
(createcompilerstub): Likewise.
(createnativestub): Likewise.

* src/vm/jit/powerpc/asmpart.S: Likewise.

* src/vm/jit/stacktrace.c (stacktrace_create_stackframeinfo):
Likewise.
(stacktrace_create_native_stackframeinfo): Likewise.
(stacktrace_add_method): Likewise.
(stacktrace_create): Likewise.

* src/vm/exceptions.c (exceptions_handle_exception): Likewise.

* src/vm/jit/codegen-common.c (codegen_findmethod): Define for all
architectures. Removed assert, we have to check that somewhere else.
(codegen_finish): Add the method for all architectures.

* src/vm/jit/codegen-common.h (methodtree_element): Likewise.

* src/vm/jit/profile/profile.c (profile_thread): First implementation.
* src/vm/jit/profile/profile.h (vm/global.h): Added.

* src/vm/signal.c (signal_init): Install SIGUSR2 for profiling.
* src/vm/signallocal.h (md_signal_handler_sigusr2): Added.
* src/vm/jit/powerpc/linux/md-os.c (md_signal_handler_sigusr2): New
method.

* src/vm/vm.c (vm_create): Call profile_start_thread only with
opt_prof.

* src/cacaoh/headers.c (exceptions_throw_nosuchmethoderror): Added.