Merged revisions 7665-7673 via svnmerge from svn+ssh://michi@c1.complang.tuwien.ac.at/ahome/cacao/svn/cacao/trunk
........
  r7666 | twisti | 2007-04-05 02:14:57 +0200 (Thu, 05 Apr 2007) | 4 lines

  * src/threads/threads-common.c (threads_print_stacktrace): Removed
  !ENABLE_THREADS code, since this file is only compiled with
  ENABLE_THREADS.
........
  r7669 | twisti | 2007-04-05 13:39:58 +0200 (Thu, 05 Apr 2007) | 27 lines

  * src/native/vm/java_lang_Thread.c [ENABLE_THREADS]
  (threads/native/threads.h): Removed.
  (threads/threads-common.h): Added.
  (vm/stringlocal.h): Likewise.
  (vm/vm.h): Removed.
  (getState): Implemented.

  * src/threads/threads-common.c (vm/vm.h): Added.
  (threads_get_state): New function.
  (threads_dump): Print thread state.

  * src/threads/threads-common.h (THREAD_STATE_NEW)
  (THREAD_STATE_RUNNABLE, THREAD_STATE_BLOCKED, THREAD_STATE_WAITING)
  (THREAD_STATE_TIMED_WAITING, THREAD_STATE_TERMINATED): Defined.
  (threads_get_state): Added.

  * src/threads/native/threads.c (threads_init): Set thread-state.
  (threads_startup_thread): Likewise.
  (threads_attach_current_thread): Likewise.
  (threads_detach_thread): Likewise.
  (threads_wait_with_timeout): Likewise.

  * src/threads/native/threads.h (threadobject): Added state field.

  * src/native/native.c (dummynativetable) [ENABLE_JAVASE]: Added
  Java_java_lang_VMThread_getState.
........
  r7670 | twisti | 2007-04-05 13:57:59 +0200 (Thu, 05 Apr 2007) | 13 lines

  * src/threads/threads-common.c (threads_get_state): Renamed to
  threads_thread_get_state.
  (threads_thread_is_alive): New function.

  * src/threads/threads-common.h: Likewise.

  * src/native/vm/java_lang_Thread.c (isAlive): New function.
  (getState): Renamed threads_get_state to threads_thread_get_state.

  * src/native/vm/java_lang_Thread.h (isAlive): Added.

  * src/native/vm/cldc1.1/java_lang_Thread.c (isAlive): New function.
........
  r7671 | twisti | 2007-04-05 14:06:28 +0200 (Thu, 05 Apr 2007) | 3 lines

  * src/vm/exceptions.c (exceptions_throw_nosuchmethoderror)
  [!ENABLE_JAVASE]: Throw an error.
........
  r7673 | michi | 2007-04-05 15:22:37 +0200 (Thu, 05 Apr 2007) | 3 lines

  * src/vm/jit/codegen-common.c (codegen_get_pv_from_pc): Inserted ifdef to fix
  compiler error with disabled threads.
........